trigger:
- main
- release/*
stages:
  - stage: build
    displayName: Execute Build
    jobs:
      - job: BuildArtifacts
        displayName: Build Project Artifacts
        variables:
          NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
          frontend.src: 'src/frontend'
          npm_config_cache: $(Pipeline.Workspace)/.npm
        pool:
          vmImage: 'windows-latest'
        steps:
          - checkout: self
            persistCredentials: true

          - task: UseDotNet@2
            inputs:
              packageType: "sdk"
              useGlobalJson: true

          - task: UseNode@1
            inputs:
              version: 14.x

          - task: DotNetCoreCLI@2
            displayName: Restore dotnet tools
            inputs:
              command: "custom"
              custom: "tool"
              arguments: "restore"

          - script: dotnet cake"
            displayName: Run Cake

          - task: GitTag@6
            displayName: "Tag Artifacts"
            condition: and(Succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
            inputs:
              workingdir: '$(SYSTEM.DEFAULTWORKINGDIRECTORY)'
              tagUser: 'pipeline'
              tagEmail: 'pipeline@localhost.email'
              tag: '$(build.buildNumber)'
              useLightweightTags: true